
CREATE TABLE database_tariff
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cost_per_month numeric(0) DEFAULT 0,
    tariff_name    VARCHAR(255)                             NOT NULL,
    max_size_bytes BIGINT,
    CONSTRAINT database_tariff_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api_tariff
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cost_per_month numeric(0) DEFAULT 0,
    tariff_name    VARCHAR(255)                             NOT NULL,
    requests_count INTEGER,
    CONSTRAINT user_api_tariff_pkey PRIMARY KEY (id)
);

CREATE TABLE usr
(
    id                 INTEGER NOT NULL,
    email              VARCHAR(255),
    is_email_confirmed BOOLEAN DEFAULT FALSE,
    jwt_refresh_token  VARCHAR(255),
    user_password      VARCHAR(255),
    username           VARCHAR(255),
    user_api_tariff_id INTEGER,
    bill_id            INTEGER,
    CONSTRAINT usr_pkey PRIMARY KEY (id)
);

CREATE TABLE user_bill_payment
(
    date         date DEFAULT CURRENT_DATE,
    sum          numeric(0),
    description  VARCHAR(255),
    user_bill_id INTEGER,
    user_id      INTEGER,
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT user_bill_payment_pkey PRIMARY KEY (id)
);

CREATE TABLE app_service_bill_payment
(
    date               date DEFAULT CURRENT_DATE,
    sum                numeric(0),
    description        VARCHAR(255),
    from_user_bill_id  INTEGER,
    to_service_bill_id INTEGER,
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT app_service_bill_payment_pkey PRIMARY KEY (id)
);

ALTER TABLE usr
    ADD CONSTRAINT uk_dfui7gxngrgwn9ewee3ogtgym UNIQUE (username);

ALTER TABLE usr
    ADD CONSTRAINT uk_g9l96r670qkidthshajdtxrqf UNIQUE (email);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence AS bigint START WITH 10 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE app_service_bill
(
    id         INTEGER NOT NULL,
    money_left numeric(19, 2),
    user_id    INTEGER,
    bill_type  VARCHAR(255),
    CONSTRAINT pk_app_service_bill PRIMARY KEY (id)
);

CREATE TABLE database
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    database_name     VARCHAR(255),
    database_password BYTEA,
    database_type     VARCHAR(255),
    tariff_id         INTEGER,
    user_id           INTEGER,
    bill_id           INTEGER,
    CONSTRAINT database_pkey PRIMARY KEY (id)
);

CREATE TABLE security_token
(
    id         INTEGER NOT NULL,
    expire     TIMESTAMP WITHOUT TIME ZONE,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    valid      BOOLEAN,
    user_id    INTEGER,
    CONSTRAINT security_token_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_key       VARCHAR(255),
    is_protected  BOOLEAN,
    database_id   INTEGER,
    user_id       INTEGER,
    bill_id       INTEGER,
    user_api_name VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT user_api_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api_request
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    http_method      VARCHAR(255),
    request_name     VARCHAR(255),
    request_template VARCHAR(255),
    user_api_id      INTEGER,
    CONSTRAINT user_api_request_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api_request_argument
(
    arg_name              VARCHAR(255),
    request_argument_type VARCHAR(255),
    api_request_id        INTEGER,
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT user_api_request_argument_pkey PRIMARY KEY (id)
);

CREATE TABLE user_bill
(
    id         INTEGER NOT NULL,
    money_left numeric(19, 2),
    user_id    INTEGER,
    CONSTRAINT pk_user_bill PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    user_id INTEGER NOT NULL,
    roles   VARCHAR(255)
);

ALTER TABLE user_api
    ADD CONSTRAINT fk3rdsom5wud031a9d2i7uec028 FOREIGN KEY (database_id) REFERENCES database (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE security_token
    ADD CONSTRAINT fk4lmylwjklidl3tgj8xok3hhjb FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database
    ADD CONSTRAINT fk8vk3i7ly6ph692aaixf2bmsnq FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE usr
    ADD CONSTRAINT fk9d0gho9svbjpw74efg2js8sc4 FOREIGN KEY (user_api_tariff_id) REFERENCES user_api_tariff (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE app_service_bill
    ADD CONSTRAINT fk_app_service_bill_on_user FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE app_service_bill_payment
    ADD CONSTRAINT fk_appservicebillpayment_on_from_user_bill FOREIGN KEY (from_user_bill_id) REFERENCES user_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE app_service_bill_payment
    ADD CONSTRAINT fk_appservicebillpayment_on_to_service_bill FOREIGN KEY (to_service_bill_id) REFERENCES app_service_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database
    ADD CONSTRAINT fk_database_on_bill FOREIGN KEY (bill_id) REFERENCES app_service_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_bill
    ADD CONSTRAINT fk_user_bill_on_user FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api
    ADD CONSTRAINT fk_userapi_on_bill FOREIGN KEY (bill_id) REFERENCES app_service_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_bill_payment
    ADD CONSTRAINT fk_userbillpayment_on_user FOREIGN KEY (user_id) REFERENCES user_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_bill_payment
    ADD CONSTRAINT fk_userbillpayment_on_user_bill FOREIGN KEY (user_bill_id) REFERENCES user_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE usr
    ADD CONSTRAINT fk_usr_on_bill FOREIGN KEY (bill_id) REFERENCES user_bill (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api
    ADD CONSTRAINT fkfkbj767ewilqxv962010nbn3b FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_role
    ADD CONSTRAINT fkfpm8swft53ulq2hl11yplpr5 FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database
    ADD CONSTRAINT fkl4rgk5jv3qp72e513ecgwfs6j FOREIGN KEY (tariff_id) REFERENCES database_tariff (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api_request_argument
    ADD CONSTRAINT fkmvjvcp6ywnaruv3wllxbe9sen FOREIGN KEY (api_request_id) REFERENCES user_api_request (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api_request
    ADD CONSTRAINT fkob9mwft0yu67c8g4f0vigygfb FOREIGN KEY (user_api_id) REFERENCES user_api (id) ON UPDATE NO ACTION ON DELETE NO ACTION;