
CREATE TABLE database_tariff
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cost_per_month numeric(0) DEFAULT 0,
    tariff_name    VARCHAR(255)                             NOT NULL,
    max_size_bytes BIGINT                                   NOT NULL,
    CONSTRAINT database_tariff_pkey PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date DEFAULT CURRENT_DATE,
    description VARCHAR(255),
    sum         numeric(19, 2),
    user_id     INTEGER,
    CONSTRAINT payment_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api_tariff
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cost_per_month numeric(0) DEFAULT 0,
    tariff_name    VARCHAR(255)                             NOT NULL,
    requests_count INTEGER,
    CONSTRAINT user_api_tariff_pkey PRIMARY KEY (id)
);

CREATE TABLE usr
(
    id                 INTEGER NOT NULL,
    email              VARCHAR(255),
    is_email_confirmed BOOLEAN,
    jwt_refresh_token  VARCHAR(255),
    money_amount       numeric(19, 2),
    user_password      VARCHAR(255),
    username           VARCHAR(255),
    user_api_tariff_id INTEGER,
    CONSTRAINT usr_pkey PRIMARY KEY (id)
);

ALTER TABLE usr
    ADD CONSTRAINT uk_dfui7gxngrgwn9ewee3ogtgym UNIQUE (username);

ALTER TABLE usr
    ADD CONSTRAINT uk_g9l96r670qkidthshajdtxrqf UNIQUE (email);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE database
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    database_name     VARCHAR(255),
    database_password BYTEA,
    database_type     VARCHAR(255),
    money_amount      numeric(19, 2),
    tariff_id         INTEGER,
    user_id           INTEGER,
    CONSTRAINT database_pkey PRIMARY KEY (id)
);

CREATE TABLE database_payments
(
    database_id INTEGER NOT NULL,
    payments_id BIGINT  NOT NULL,
    CONSTRAINT database_payments_pkey PRIMARY KEY (database_id, payments_id)
);

CREATE TABLE security_token
(
    id         INTEGER NOT NULL,
    expire     TIMESTAMP WITHOUT TIME ZONE,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    valid      BOOLEAN,
    user_id    INTEGER,
    CONSTRAINT security_token_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_key      VARCHAR(255),
    is_protected BOOLEAN,
    money_amount numeric(19, 2),
    name         VARCHAR(255),
    database_id  INTEGER,
    user_id      INTEGER,
    CONSTRAINT user_api_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api_payments
(
    user_api_id INTEGER NOT NULL,
    payments_id BIGINT  NOT NULL,
    CONSTRAINT user_api_payments_pkey PRIMARY KEY (user_api_id, payments_id)
);

CREATE TABLE user_api_request
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    http_method      VARCHAR(255),
    request_name     VARCHAR(255),
    request_template VARCHAR(255),
    user_api_id      INTEGER,
    CONSTRAINT user_api_request_pkey PRIMARY KEY (id)
);

CREATE TABLE user_api_request_argument
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    arg_name              VARCHAR(255),
    request_argument_type VARCHAR(255)                            NOT NULL,
    api_request_id        INTEGER,
    CONSTRAINT user_api_request_argument_pkey PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    user_id INTEGER NOT NULL,
    roles   VARCHAR(255)
);

ALTER TABLE user_api
    ADD CONSTRAINT fk3rdsom5wud031a9d2i7uec028 FOREIGN KEY (database_id) REFERENCES database (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE security_token
    ADD CONSTRAINT fk4lmylwjklidl3tgj8xok3hhjb FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database
    ADD CONSTRAINT fk8vk3i7ly6ph692aaixf2bmsnq FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE usr
    ADD CONSTRAINT fk9d0gho9svbjpw74efg2js8sc4 FOREIGN KEY (user_api_tariff_id) REFERENCES user_api_tariff (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database_payments
    ADD CONSTRAINT fkcppfkfn9diqak7nmug0cqjbui FOREIGN KEY (database_id) REFERENCES database (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api
    ADD CONSTRAINT fkfkbj767ewilqxv962010nbn3b FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_role
    ADD CONSTRAINT fkfpm8swft53ulq2hl11yplpr5 FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE payment
    ADD CONSTRAINT fkiucxucr095xqfqrpqd5a7dc96 FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database
    ADD CONSTRAINT fkl4rgk5jv3qp72e513ecgwfs6j FOREIGN KEY (tariff_id) REFERENCES database_tariff (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api_request_argument
    ADD CONSTRAINT fkmvjvcp6ywnaruv3wllxbe9sen FOREIGN KEY (api_request_id) REFERENCES user_api_request (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api_payments
    ADD CONSTRAINT fko97ddr4qe2lkm7aw8uyks4s3n FOREIGN KEY (payments_id) REFERENCES payment (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api_request
    ADD CONSTRAINT fkob9mwft0yu67c8g4f0vigygfb FOREIGN KEY (user_api_id) REFERENCES user_api (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_api_payments
    ADD CONSTRAINT fkobocmem56c0mq4onbf4gbs4qh FOREIGN KEY (user_api_id) REFERENCES user_api (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE database_payments
    ADD CONSTRAINT fkrlw4lbktl0ni57wolywst9bge FOREIGN KEY (payments_id) REFERENCES payment (id) ON UPDATE NO ACTION ON DELETE NO ACTION;