
CREATE TABLE app_service_bill
(
    id         INTEGER NOT NULL,
    money_left DECIMAL(19, 2),
    user_id    INTEGER,
    bill_type  VARCHAR(255),
    CONSTRAINT pk_app_service_bill PRIMARY KEY (id)
);

CREATE TABLE user_bill
(
    id         INTEGER NOT NULL,
    money_left DECIMAL(19, 2),
    user_id    INTEGER,
    CONSTRAINT pk_user_bill PRIMARY KEY (id)
);

CREATE TABLE user_bill_payment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date         date DEFAULT current_date,
    sum          DECIMAL,
    description  VARCHAR(255),
    user_bill_id INTEGER,
    user_id      INTEGER,
    CONSTRAINT pk_userbillpayment PRIMARY KEY (id)
);

CREATE TABLE user_bill_to_app_service_bill_payment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date               date DEFAULT current_date,
    sum                DECIMAL,
    description        VARCHAR(255),
    from_user_bill_id  INTEGER,
    to_service_bill_id INTEGER,
    CONSTRAINT pk_userbilltoappservicebillpayment PRIMARY KEY (id)
);

ALTER TABLE database
    ADD bill_id INTEGER;

ALTER TABLE user_api
    ADD bill_id INTEGER;

ALTER TABLE user_api
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE user_api
    ADD user_api_name VARCHAR(255);

ALTER TABLE usr
    ADD bill_id INTEGER;

ALTER TABLE user_api
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE user_api
    ADD user_api_name VARCHAR(255);

ALTER TABLE app_service_bill
    ADD CONSTRAINT FK_APP_SERVICE_BILL_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);

ALTER TABLE database
    ADD CONSTRAINT FK_DATABASE_ON_BILL FOREIGN KEY (bill_id) REFERENCES app_service_bill (id);

ALTER TABLE user_api
    ADD CONSTRAINT FK_USERAPI_ON_BILL FOREIGN KEY (bill_id) REFERENCES app_service_bill (id);

ALTER TABLE user_bill_payment
    ADD CONSTRAINT FK_USERBILLPAYMENT_ON_USER FOREIGN KEY (user_id) REFERENCES user_bill (id);

ALTER TABLE user_bill_payment
    ADD CONSTRAINT FK_USERBILLPAYMENT_ON_USER_BILL FOREIGN KEY (user_bill_id) REFERENCES user_bill (id);

ALTER TABLE user_bill_to_app_service_bill_payment
    ADD CONSTRAINT FK_USERBILLTOAPPSERVICEBILLPAYMENT_ON_FROM_USER_BILL FOREIGN KEY (from_user_bill_id) REFERENCES user_bill (id);

ALTER TABLE user_bill_to_app_service_bill_payment
    ADD CONSTRAINT FK_USERBILLTOAPPSERVICEBILLPAYMENT_ON_TO_SERVICE_BILL FOREIGN KEY (to_service_bill_id) REFERENCES app_service_bill (id);

ALTER TABLE user_bill
    ADD CONSTRAINT FK_USER_BILL_ON_USER FOREIGN KEY (user_id) REFERENCES usr (id);

ALTER TABLE usr
    ADD CONSTRAINT FK_USR_ON_BILL FOREIGN KEY (bill_id) REFERENCES user_bill (id);

ALTER TABLE database_payments
    DROP CONSTRAINT fkcppfkfn9diqak7nmug0cqjbui;

ALTER TABLE payment
    DROP CONSTRAINT fkiucxucr095xqfqrpqd5a7dc96;

ALTER TABLE user_api_payments
    DROP CONSTRAINT fko97ddr4qe2lkm7aw8uyks4s3n;

ALTER TABLE user_api_payments
    DROP CONSTRAINT fkobocmem56c0mq4onbf4gbs4qh;

ALTER TABLE database_payments
    DROP CONSTRAINT fkrlw4lbktl0ni57wolywst9bge;

DROP TABLE database_payments CASCADE;

DROP TABLE payment CASCADE;

DROP TABLE user_api_payments CASCADE;

ALTER TABLE database
    DROP COLUMN money_amount;

ALTER TABLE user_api
    DROP COLUMN money_amount;

ALTER TABLE usr
    DROP COLUMN money_amount;