ALTER TABLE database
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE user_api_request_argument
    DROP COLUMN id;

ALTER TABLE user_api_request_argument
    ADD id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE database_tariff
    ALTER COLUMN max_size_bytes DROP NOT NULL;

ALTER TABLE user_api_request_argument
    ALTER COLUMN request_argument_type DROP NOT NULL;